# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks



# Global properties

separator=true
separator_block_width=15

#[title]
#label=
#command=sh ~/.config/i3/title.sh
#interval=1

#[close-window]
#full_text=
#command=xdotool key super+shift+q

[wifi]
command=i3status -c ~/.config/i3/i3statuswifi.conf
interval=persist

[ethernet]
command=i3status -c ~/.config/i3/i3statusethernet.conf
interval=persist

[numlock]
command=perl ~/.config/i3/lockkey.perl
markup=pango
KEY=NUM
interval=once
signal=11
HIDE_WHEN_OFF=1

[capslock]
command=perl ~/.config/i3/lockkey.perl
markup=pango
interval=once
signal=11
HIDE_WHEN_OFF=1

[cpu]
command=sh ~/.config/i3/cpu.sh
markup=pango
interval=5

[temp]
command=perl ~/.config/i3/temp.perl
label= 
interval=10

[memory]
command=sh ~/.config/i3/ram.sh
label= 
interval=10

[battery]
command=python3 ~/.config/i3/battery.py
#command=sh ~/Public/powerprofiles.sh
markup=pango
interval=30

[brightness]
label= 
command=sh ~/.config/i3/brightness.sh
interval=1

[volume]
command=sh ~/.config/i3/volume.sh
interval=1

[communication]
command=sh ~/.config/i3/communication.sh
interval=1

[time]
label= 
#command=sh ~/.config/i3/date.sh
command=date '+%a %b %d %H:%M:%S'
interval=1

[keyboard]
command=sh ~/.config/i3/keylayout.sh
interval=1
markup=pango

#[test]
#command=~/test
#interval=1

[power-button]
full_text= 
command=sh ~/.config/i3/powermenu.sh
