require("packers")

require("ui.vscodetheme")
--require("ui.dracula")
require("ui.alpha")
require("ui.lualine")
require("ui.bufferline")
require("ui.devicons")
--require("ui.noice")
--require("ui.dashboard")
--require("ui.scrollbar")

--require("lsp.cmp")
--require("lsp.copilot")
require("lsp.lspconfig")
--require("lsp.mason")
require("lsp.null-ls")
require("lsp.signature")
require("lsp.luasnip")

require("coding.autopairs")
require("coding.dap")
require("coding.ufo")
require("coding.coderunner")
require("coding.treesitter")
--require("coding.identblankline")
require("coding.filetype")
--require("coding.gitsigns")

require("browser.project")
require("browser.telescope")
require("browser.nvimtree")
