windowrule = bordercolor rgb(7287fd) rgb(8caaee) 90deg, foot

windowrule = bordercolor rgb(fff14c) rgb(e60a73) 90deg, firefox
windowrule = bordercolor rgb(73eafe) rgb(0259d2) 90deg, firefox-developer-edition
windowrule = bordercolor rgb(00acff), LibreWolf
windowrule = bordercolor rgb(ff2801), brave-browser

windowrule = bordercolor rgb(fe2857) rgb(007eff) rgb(007eff) 135deg, jetbrains-idea-ce
windowrule = bordercolor rgb(f0eb18) rgb(00c4f4) rgb(00c4f4) 135deg, jetbrains-pycharm-ce

windowrule = bordercolor rgb(f462a3), osu!
