windowrule = rounding 15, eww_power_dialog
windowrule = stayfocused, eww_power_dialog
windowrule = pin, eww_power_dialog

windowrule = stayfocused, wofi
windowrule = pin, wofi

windowrulev2 = noblur 1, class:.*
windowrulev2 = animation popin, floating: 1
windowrulev2 = workspace unset, floating: 1
windowrule = noborder, Xdg-desktop-portal-gtk
windowrulev2 = rounding 0, class:^$, title:^$

# Workspace 1: terminal
windowrule = noblur 0, foot
windowrule = noblur 0, footclient
windowrule = noblur 0, com.mitchellh.ghostty

windowrulev2 = tile, class:^(Alacritty)$
windowrulev2 = workspace 1, class:^(Alacritty)$
windowrule = workspace 1, foot
windowrule = workspace 1, footclient
windowrule = workspace 1, Gnome-terminal
windowrule = workspace 1, com.mitchellh.ghostty


# Workspace 2: browsers
windowrulev2 = workspace 2, class:^(firefox)$, floating: 0
windowrule = workspace 2, Chromium
windowrule = workspace 2, LibreWolf
windowrule = workspace 2, brave-browser
windowrule = workspace 2, Google-chrome
windowrule = workspace 2, firefox-developer-edition

# Workspace 3: text editors
windowrulev2 = workspace 3, class:^(code-oss)$
windowrulev2 = workspace 3, class:^(codeblocks)$
windowrulev2 = float, class:^(codeblocks-console)$
windowrulev2 = workspace 3, class:^(codeblocks-console)$

windowrule = workspace 3, Eclipse
windowrulev2 = float, class:^(java)$, title:^(Eclipse)$

windowrulev2 = workspace 3, class:^(DBeaver)$

windowrulev2 = tile, class:^(Apache NetBeans IDE.*)$
windowrulev2 = workspace 3, class:^(Apache NetBeans IDE.*)$

windowrule = workspace 3, Nvim
windowrule = workspace 3, Emacs
windowrule = workspace 3, nvim-qt
windowrule = workspace 3, Mysql-workbench-bin

windowrulev2 = workspace 3 silent, class:^(Java)$, title:^(Dbeaver)$
windowrulev2 = workspace 3 silent, class:^(java)$, title:^(Eclipse)$
windowrulev2 = workspace 3 silent, title:^(Starting Apache NetBeans IDE)$

#windowrulev2 = tile, class:^(jetbrains-.*)$, title:^(+*)$, initialTitle: ^()$
#windowrulev2 = tile, class:^(jetbrains-.*)$, title:^(Welcome to .*)$
windowrulev2 = workspace 3, class:^(jetbrains-.*)$

windowrulev2 = norounding 1, class:^(jetbrains-.*)$, title:^(win[0-9]+)$
windowrulev2 = noinitialfocus, class:^(jetbrains-.*)$, title:^(win[0-9]+)$
windowrulev2 = workspace unset, class:^(jetbrains-.*)$, title:^(win[0-9]+)$

windowrulev2 = workspace 3 silent, class:^(jetbrains-.*)$, title:^(splash)$

windowrule = float, matplotlib

# Workspace 4: file-related apps
windowrule = workspace 4, nemo
windowrule = workspace 4, Nautilus
windowrule = workspace 4, qBittorrent

# Workspace 5: media
windowrule = workspace 5, Gnome-screenshot
windowrule = workspace 5, obs
windowrule = workspace 5, vlc

# Workspace 6: games
windowrule = tile, deadcells
windowrule = workspace 6, deadcells
windowrulev2 = tile, title:^(Minecraft.*)$, class:^(Minecraft.*)$
windowrulev2 = workspace 6, title:^(Minecraft.*)$, class:^(Minecraft.*)$
windowrule = workspace 6, org-tlauncher-tlauncher-rmo-TLauncher
windowrule = workspace 6, osu!

# Workspace 7: meeting
windowrule = workspace 7, discord
windowrulev2 = workspace silent 7, class:^(zoom)$
windowrule = workspace silent 7, Microsoft Teams - Preview
