"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'arch'

format = """
[(\\[$username$hostname\\])](line)$directory\
[(\n[┆](line) $all)]()\
$line_break[└╼](line) \
"""

[palettes.arch]
line = "cyan"

[battery]
disabled = true

[character]
disabled = true

[directory]
style = "bright-purple"
format = '[[─\[](line)$path[$read_only]($read_only_style)[\]](line)]($style)'
read_only = " "
truncation_length = 15
truncation_symbol = '.../'

[cmd_duration]
min_time = 0

[git_branch]
symbol = '[ ](#f05033)'
style = ""

[git_status]
deleted	= '-'
style = "#f2301b"
format = '([$all_status$ahead_behind]($style) )'

[username]
style_user = '10 bold'
style_root = '11 bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
format = '[$ssh_symbol](bold blue)[@](bold 8)[$hostname](bold 12)'
ssh_only = false

[nodejs]
detect_extensions = []
detect_files = ['package-lock.json', '.node-version']
detect_folders = []

[status]
format = '[$int]($style)[[: ]()$common_meaning$signal_name$maybe_int](#f0c6c6) '
style = 'bold bright-red'
map_symbol = true
disabled = false

[c]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[python]
symbol = " "

[rust]
symbol = "󱘗 "
