"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[╭─](line)${env_var.CMD_COUNT}\
[(\\[$username$hostname\\])](line)$directory\
[(\n[┆](line) $all)]()\
$line_break[╰╼](line) ${env_var.SH_CHAR} \
"""

palette = 'arch'

[palettes.arch]
line = "cyan"

[env_var.CMD_COUNT]
format = "[([\\[](line)$env_value[\\]](line))]($style)"
style = "bright-white bold"

[env_var.SH_CHAR]
format = "[$env_value]($style)"
style = "bright-cyan bold"
default = "$"

[character]
disabled = true

[directory]
style = "bright-purple"
format = '[[─\[](line)$path[$read_only]($read_only_style)[\]](line)]($style)'
read_only = " "
truncation_length = 20
truncation_symbol = '.../'

[cmd_duration]
min_time = 0
show_milliseconds = true

[git_branch]
symbol = '[](#f05033) '
style = ""

[git_status]
deleted	= '-'
style = "#f2301b"
format = '([$all_status$ahead_behind]($style) )'

[username]
style_user = '10 bold'
style_root = '11 bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
format = '[$ssh_symbol](bold blue)[@](bold 8)[$hostname](bold 12)'
ssh_only = false

[nodejs]
detect_extensions = []
detect_files = ['package-lock.json', '.node-version']
detect_folders = []

[status]
format = '[$int](bold bright-red)[[: ]()$common_meaning$signal_name$maybe_int](#f0c6c6) '
map_symbol = true
disabled = false

[c]
symbol = " "

[conda]
symbol = " "
ignore_base = false

[golang]
symbol = " "

[gradle]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[sudo]
format = 'as [$symbol]($style) '
symbol = ""
disabled = false
